import type { ProcessOptions } from './dither';

export interface Preset {
  id: string;
  name: string;
  description: string;
  emoji: string;
  paletteId: string;
  opts: Partial<ProcessOptions>;
}

export const PRESETS: Preset[] = [
  {
    id: 'gameboy_classic',
    name: 'Game Boy',
    description: 'Original DMG-01 greenscale with Bayer 4x4',
    emoji: '🎮',
    paletteId: 'gameboy',
    opts: {
      pixelSize: 4,
      algorithm: 'bayer4',
      ditherStrength: 0.8,
      brightness: 0,
      contrast: 20,
      saturation: -80,
      localContrast: 30,
      aspectRatio: '1:1',
    },
  },
  {
    id: 'gameboy_photo',
    name: 'GB Camera',
    description: 'Like the Game Boy Camera with heavy dithering',
    emoji: '📷',
    paletteId: 'gameboy',
    opts: {
      pixelSize: 3,
      algorithm: 'floyd_steinberg',
      ditherStrength: 1.0,
      brightness: 10,
      contrast: 40,
      saturation: -100,
      localContrast: 50,
      aspectRatio: '1:1',
    },
  },
  {
    id: 'gameboy_pocket',
    name: 'GB Pocket',
    description: 'Game Boy Pocket true grey with Atkinson dithering',
    emoji: '⬜',
    paletteId: 'gameboy_pocket',
    opts: {
      pixelSize: 4,
      algorithm: 'atkinson',
      ditherStrength: 0.75,
      brightness: 5,
      contrast: 15,
      saturation: -100,
      localContrast: 20,
      aspectRatio: '1:1',
    },
  },
  {
    id: 'gba_vivid',
    name: 'Game Boy Advance',
    description: 'GBA style with rich colors',
    emoji: '🕹️',
    paletteId: 'gba',
    opts: {
      pixelSize: 3,
      algorithm: 'floyd_steinberg',
      ditherStrength: 0.7,
      brightness: 0,
      contrast: 10,
      saturation: 30,
      localContrast: 20,
      aspectRatio: '1:1',
    },
  },
  {
    id: 'nes_nostalgic',
    name: 'NES',
    description: 'Nintendo Entertainment System look',
    emoji: '🎰',
    paletteId: 'nes',
    opts: {
      pixelSize: 4,
      algorithm: 'bayer4',
      ditherStrength: 0.6,
      brightness: 0,
      contrast: 20,
      saturation: 20,
      localContrast: 25,
      aspectRatio: '1:1',
    },
  },
  {
    id: 'snes_16bit',
    name: 'SNES 16-bit',
    description: 'Super Nintendo smooth gradients',
    emoji: '🦕',
    paletteId: 'snes',
    opts: {
      pixelSize: 3,
      algorithm: 'floyd_steinberg',
      ditherStrength: 0.8,
      brightness: 0,
      contrast: 5,
      saturation: 20,
      localContrast: 15,
      aspectRatio: '1:1',
    },
  },
  {
    id: 'genesis_sonic',
    name: 'Sega Genesis',
    description: 'Mega Drive bold contrast look',
    emoji: '🦔',
    paletteId: 'sega_genesis',
    opts: {
      pixelSize: 4,
      algorithm: 'bayer4',
      ditherStrength: 0.5,
      brightness: -5,
      contrast: 30,
      saturation: 40,
      localContrast: 30,
      aspectRatio: '1:1',
    },
  },
  {
    id: 'gamegear',
    name: 'Game Gear',
    description: 'Sega Game Gear handheld look',
    emoji: '📺',
    paletteId: 'game_gear',
    opts: {
      pixelSize: 3,
      algorithm: 'floyd_steinberg',
      ditherStrength: 0.7,
      brightness: 5,
      contrast: 15,
      saturation: 30,
      localContrast: 20,
      aspectRatio: '1:1',
    },
  },
  {
    id: 'cga_cyan',
    name: 'CGA Mode',
    description: 'IBM PC CGA 16-color classic',
    emoji: '💾',
    paletteId: 'cga',
    opts: {
      pixelSize: 5,
      algorithm: 'bayer8',
      ditherStrength: 0.9,
      brightness: 0,
      contrast: 25,
      saturation: 0,
      localContrast: 20,
      aspectRatio: '1:2',
    },
  },
  {
    id: 'zx_spectrum',
    name: 'ZX Spectrum',
    description: 'Sinclair ZX Spectrum bright chunky pixels',
    emoji: '🌈',
    paletteId: 'zx_spectrum',
    opts: {
      pixelSize: 6,
      algorithm: 'checkerboard',
      ditherStrength: 0.8,
      brightness: 10,
      contrast: 30,
      saturation: 50,
      localContrast: 30,
      aspectRatio: '1:1',
    },
  },
  {
    id: 'commodore64',
    name: 'Commodore 64',
    description: 'C64 VIC-II classic home computer look',
    emoji: '🖱️',
    paletteId: 'c64',
    opts: {
      pixelSize: 5,
      algorithm: 'floyd_steinberg',
      ditherStrength: 0.85,
      brightness: 5,
      contrast: 20,
      saturation: 10,
      localContrast: 25,
      aspectRatio: '2:1',
    },
  },
  {
    id: 'pico8_fantasy',
    name: 'PICO-8',
    description: 'Fantasy console indie look',
    emoji: '🐱',
    paletteId: 'pico8',
    opts: {
      pixelSize: 5,
      algorithm: 'bayer4',
      ditherStrength: 0.7,
      brightness: 5,
      contrast: 15,
      saturation: 60,
      localContrast: 20,
      aspectRatio: '1:1',
    },
  },
  {
    id: 'mac_bw',
    name: 'Mac 1-bit',
    description: 'Original Macintosh 1-bit monochrome with Floyd-Steinberg',
    emoji: '🖥',
    paletteId: 'macintosh',
    opts: {
      pixelSize: 2,
      algorithm: 'floyd_steinberg',
      ditherStrength: 1.0,
      brightness: 0,
      contrast: 30,
      saturation: -100,
      localContrast: 40,
      aspectRatio: '1:1',
    },
  },
  {
    id: 'phosphor_green',
    name: 'Phosphor Green',
    description: 'Old-school green phosphor terminal monitor',
    emoji: '📟',
    paletteId: 'monochrome_green',
    opts: {
      pixelSize: 2,
      algorithm: 'atkinson',
      ditherStrength: 0.9,
      brightness: -10,
      contrast: 40,
      saturation: -100,
      localContrast: 30,
      aspectRatio: '1:1',
    },
  },
  {
    id: 'amber_monitor',
    name: 'Amber Phosphor',
    description: 'Classic amber terminal glow',
    emoji: '🟡',
    paletteId: 'monochrome_amber',
    opts: {
      pixelSize: 2,
      algorithm: 'atkinson',
      ditherStrength: 0.9,
      brightness: -5,
      contrast: 35,
      saturation: -100,
      localContrast: 30,
      aspectRatio: '1:1',
    },
  },
  {
    id: 'glitch_art',
    name: 'Glitch Art',
    description: 'CGA + maximum glitch effects',
    emoji: '💥',
    paletteId: 'cga',
    opts: {
      pixelSize: 6,
      algorithm: 'noise',
      ditherStrength: 1.0,
      brightness: 0,
      contrast: 40,
      saturation: 80,
      localContrast: 50,
      aspectRatio: '1:1',
      glitch: {
        rgbShift: 12,
        scanlines: true,
        pixelScatter: 5,
        interlace: true,
        vhsBlur: 4,
      },
    },
  },
  {
    id: 'vhs_tape',
    name: 'VHS Tape',
    description: 'Washed-out VHS aesthetic with scanlines',
    emoji: '📼',
    paletteId: 'sega_genesis',
    opts: {
      pixelSize: 2,
      algorithm: 'noise',
      ditherStrength: 0.4,
      brightness: -10,
      contrast: -20,
      saturation: 30,
      localContrast: 10,
      aspectRatio: '1:1',
      glitch: {
        rgbShift: 4,
        scanlines: true,
        pixelScatter: 2,
        interlace: false,
        vhsBlur: 7,
      },
    },
  },
  {
    id: 'amstrad_art',
    name: 'Amstrad CPC',
    description: 'Amstrad CPC 6128 27-color palette',
    emoji: '🖨️',
    paletteId: 'amstrad',
    opts: {
      pixelSize: 4,
      algorithm: 'floyd_steinberg',
      ditherStrength: 0.8,
      brightness: 0,
      contrast: 20,
      saturation: 30,
      localContrast: 25,
      aspectRatio: '1:1',
    },
  },
];
